# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Extractor

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: amir9979/coming
        path: .
        fetch-depth: 0
        ref: main

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn install -DskipTests
    
    - name: Checkout tools repo
      continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.issue.title}}
        path: ./my-tools
        fetch-depth: 0
    
    - name: fetch  
      continue-on-error: true
      run: git fetch
      working-directory: ./my-tools

    - name: out_dir
      run: mkdir out_dir

    - name: execute
      run: |
        java -cp target\coming-0-SNAPSHOT-jar-with-dependencies.jar  fr.inria.coming.main.ComingMain -location my-tools -mode mineinstance -pattern patterns\ep_9.xml -output out_dir\ep_9
        java -cp target\coming-0-SNAPSHOT-jar-with-dependencies.jar  fr.inria.coming.main.ComingMain -location my-tools -mode mineinstance -pattern patterns\ep_8.xml -output out_dir\ep_8

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: out_dir
        # A file, directory or wildcard pattern that describes what to upload
        path: out_dir


    - name: Close Issue
      continue-on-error: true
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          The issue you have reported seems to be resolved now.
